<script setup lang="ts">
import type { DashboardData } from '~/types/api';
const { request } = useApi(); const data = ref<DashboardData>(); const loading = ref(true);
onMounted(async () => { try { data.value = await request<DashboardData>('/dashboard'); } finally { loading.value = false; } });
function date(value?: string) { return value ? new Intl.DateTimeFormat('zh-CN', { dateStyle: 'medium' }).format(new Date(value)) : ''; }
</script>

<template>
  <main class="wp-container py-10"><section class="mb-8"><p class="text-sm font-semibold uppercase tracking-[.2em] text-emerald-700">Team Library</p><h1 class="mt-2 text-4xl font-bold">今天，读点值得留下的。</h1><p class="mt-3 text-gray-500">来自公众号与网页的内容，已经被整理到同一个地方。</p></section><div v-if="loading" class="py-20 text-center text-gray-500">正在加载…</div><template v-else-if="data"><section class="grid gap-4 sm:grid-cols-2 lg:grid-cols-4"><div class="wp-card p-5"><p class="text-sm text-gray-500">内容总数</p><p class="mt-2 text-3xl font-bold">{{ data.articlesTotal }}</p></div><div class="wp-card p-5"><p class="text-sm text-gray-500">今日新增</p><p class="mt-2 text-3xl font-bold">{{ data.collectedToday }}</p></div><div class="wp-card p-5"><p class="text-sm text-gray-500">公众号文章</p><p class="mt-2 text-3xl font-bold">{{ data.sourceWechat }}</p></div><div class="wp-card p-5"><p class="text-sm text-gray-500">普通网页</p><p class="mt-2 text-3xl font-bold">{{ data.sourceWeb }}</p></div></section><section class="mt-10"><div class="mb-4 flex items-end justify-between"><div><h2 class="text-2xl font-bold">最近收录</h2><p class="mt-1 text-sm text-gray-500">最新进入团队内容库的文章</p></div><NuxtLink class="text-sm font-medium text-emerald-700" to="/articles">查看全部 →</NuxtLink></div><div class="grid gap-4 md:grid-cols-2"><NuxtLink v-for="article in data.recentArticles" :key="article.id" :to="`/articles/${article.id}`" class="wp-card group p-6 hover:border-emerald-700/40"><div class="mb-3 flex items-center gap-2 text-xs text-gray-500"><span class="rounded-full bg-emerald-50 px-2 py-1 text-emerald-700">{{ article.sourceType === 'wechat' ? '公众号' : '网页' }}</span><span>{{ date(article.publishedAt || article.createdAt) }}</span></div><h3 class="text-xl font-bold leading-snug group-hover:text-emerald-700">{{ article.title }}</h3><p class="mt-3 text-sm text-gray-500">{{ article.sourceName || article.author || '未知来源' }}</p></NuxtLink><div v-if="!data.recentArticles.length" class="wp-card col-span-full py-16 text-center text-gray-500">还没有收录内容，请先在管理后台提交文章。</div></div></section></template></main>
</template>
