<script setup lang="ts">
const route = useRoute(); const auth = useAuthStore(); const username = ref(''); const password = ref(''); const error = ref('');
useSeoMeta({ title: '登录内容前台｜WeavePress', robots: 'noindex, nofollow' });
async function submit() { error.value = ''; try { await auth.login(username.value.trim(), password.value); await navigateTo(resolvePostLoginPath(typeof route.query.redirect === 'string' ? route.query.redirect : undefined)); } catch (reason: unknown) { const failure = reason as { data?: { message?: string } } | null; error.value = failure?.data?.message || '登录失败，请检查用户名和密码'; } }
</script>

<template>
  <main class="grid min-h-screen place-items-center bg-slate-50 p-6"><section class="wp-card w-full max-w-md p-8 sm:p-10"><NuxtLink to="/" class="inline-flex items-center gap-3 font-bold"><span class="grid size-11 place-items-center rounded-2xl bg-indigo-600 text-xl text-white">织</span><span>WeavePress</span></NuxtLink><div class="mb-8 mt-8"><h1 class="text-3xl font-bold">进入内容前台</h1><p class="mt-2 text-gray-500">使用管理员分配的内部账号登录团队内容中心。</p></div><form class="space-y-5" @submit.prevent="submit"><label class="block"><span class="mb-2 block text-sm font-medium">用户名</span><input v-model="username" autocomplete="username" class="w-full rounded-xl border border-black/15 bg-white px-4 py-3 outline-none focus:border-indigo-600" required></label><label class="block"><span class="mb-2 block text-sm font-medium">密码</span><input v-model="password" autocomplete="current-password" class="w-full rounded-xl border border-black/15 bg-white px-4 py-3 outline-none focus:border-indigo-600" minlength="8" required type="password"></label><p v-if="error" class="rounded-lg bg-red-50 p-3 text-sm text-red-700">{{ error }}</p><button class="w-full rounded-xl bg-indigo-600 px-4 py-3 font-medium text-white hover:bg-indigo-700 disabled:opacity-60" :disabled="auth.busy">{{ auth.busy ? '登录中…' : '登录' }}</button></form><a class="mt-5 block text-center text-sm text-slate-500 hover:text-indigo-600" href="/admin/">需要管理内容？进入管理后台 →</a></section></main>
</template>
