// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package sqlc

import (
	"database/sql"
	"encoding/json"
	"time"
)

type Article struct {
	ID               uint64          `json:"id"`
	OriginalUrl      string          `json:"original_url"`
	CanonicalUrl     string          `json:"canonical_url"`
	CanonicalUrlHash []byte          `json:"canonical_url_hash"`
	SourceType       string          `json:"source_type"`
	Title            string          `json:"title"`
	Author           string          `json:"author"`
	SourceName       string          `json:"source_name"`
	Language         string          `json:"language"`
	PublishedAt      sql.NullTime    `json:"published_at"`
	PlainText        string          `json:"plain_text"`
	CleanHtml        string          `json:"clean_html"`
	BlocksJson       json.RawMessage `json:"blocks_json"`
	MetadataJson     json.RawMessage `json:"metadata_json"`
	RawObjectKey     string          `json:"raw_object_key"`
	ContentHash      sql.NullString  `json:"content_hash"`
	Status           string          `json:"status"`
	DuplicateOfID    sql.NullInt64   `json:"duplicate_of_id"`
	CreatedBy        uint64          `json:"created_by"`
	CreatedAt        time.Time       `json:"created_at"`
	UpdatedAt        time.Time       `json:"updated_at"`
}

type ArticleAsset struct {
	ID             uint64    `json:"id"`
	ArticleID      uint64    `json:"article_id"`
	SourceUrl      string    `json:"source_url"`
	SourceUrlHash  []byte    `json:"source_url_hash"`
	ObjectKey      string    `json:"object_key"`
	MediaType      string    `json:"media_type"`
	ByteSize       uint64    `json:"byte_size"`
	Width          uint32    `json:"width"`
	Height         uint32    `json:"height"`
	Sha256         []byte    `json:"sha256"`
	Position       uint32    `json:"position"`
	IsCover        bool      `json:"is_cover"`
	DownloadStatus string    `json:"download_status"`
	CreatedAt      time.Time `json:"created_at"`
}

type AuthRefreshToken struct {
	ID             uint64         `json:"id"`
	UserID         uint64         `json:"user_id"`
	FamilyID       string         `json:"family_id"`
	TokenHash      []byte         `json:"token_hash"`
	ReplacedByHash sql.NullString `json:"replaced_by_hash"`
	UserAgent      string         `json:"user_agent"`
	IpAddress      string         `json:"ip_address"`
	ExpiresAt      time.Time      `json:"expires_at"`
	RevokedAt      sql.NullTime   `json:"revoked_at"`
	CreatedAt      time.Time      `json:"created_at"`
}

type CollectionJob struct {
	ID            uint64          `json:"id"`
	ArticleID     uint64          `json:"article_id"`
	SubmittedBy   uint64          `json:"submitted_by"`
	Status        string          `json:"status"`
	Attempts      uint32          `json:"attempts"`
	ManualRetries uint32          `json:"manual_retries"`
	ErrorCode     string          `json:"error_code"`
	ErrorMessage  string          `json:"error_message"`
	WarningsJson  json.RawMessage `json:"warnings_json"`
	StartedAt     sql.NullTime    `json:"started_at"`
	FinishedAt    sql.NullTime    `json:"finished_at"`
	CreatedAt     time.Time       `json:"created_at"`
	UpdatedAt     time.Time       `json:"updated_at"`
}

type CollectionJobEvent struct {
	ID        uint64    `json:"id"`
	JobID     uint64    `json:"job_id"`
	Status    string    `json:"status"`
	Message   string    `json:"message"`
	CreatedAt time.Time `json:"created_at"`
}

type Draft struct {
	ID              uint64        `json:"id"`
	SourceArticleID uint64        `json:"source_article_id"`
	Title           string        `json:"title"`
	Author          string        `json:"author"`
	Digest          string        `json:"digest"`
	ContentHtml     string        `json:"content_html"`
	CoverAssetID    sql.NullInt64 `json:"cover_asset_id"`
	Status          string        `json:"status"`
	CurrentVersion  uint32        `json:"current_version"`
	CreatedBy       uint64        `json:"created_by"`
	UpdatedBy       uint64        `json:"updated_by"`
	CreatedAt       time.Time     `json:"created_at"`
	UpdatedAt       time.Time     `json:"updated_at"`
}

type DraftEvent struct {
	ID         uint64    `json:"id"`
	DraftID    uint64    `json:"draft_id"`
	ActorID    uint64    `json:"actor_id"`
	FromStatus string    `json:"from_status"`
	ToStatus   string    `json:"to_status"`
	Note       string    `json:"note"`
	CreatedAt  time.Time `json:"created_at"`
}

type DraftVersion struct {
	ID           uint64        `json:"id"`
	DraftID      uint64        `json:"draft_id"`
	Version      uint32        `json:"version"`
	Title        string        `json:"title"`
	Author       string        `json:"author"`
	Digest       string        `json:"digest"`
	ContentHtml  string        `json:"content_html"`
	CoverAssetID sql.NullInt64 `json:"cover_asset_id"`
	ChangeNote   string        `json:"change_note"`
	CreatedBy    uint64        `json:"created_by"`
	CreatedAt    time.Time     `json:"created_at"`
}

type User struct {
	ID           uint64    `json:"id"`
	Username     string    `json:"username"`
	PasswordHash string    `json:"password_hash"`
	Nickname     string    `json:"nickname"`
	Avatar       string    `json:"avatar"`
	Role         string    `json:"role"`
	Status       string    `json:"status"`
	CreatedAt    time.Time `json:"created_at"`
	UpdatedAt    time.Time `json:"updated_at"`
}

type WechatPublishJob struct {
	ID            uint64       `json:"id"`
	DraftID       uint64       `json:"draft_id"`
	RequestedBy   uint64       `json:"requested_by"`
	Status        string       `json:"status"`
	Attempts      uint32       `json:"attempts"`
	ManualRetries uint32       `json:"manual_retries"`
	RemoteMediaID string       `json:"remote_media_id"`
	ErrorCode     string       `json:"error_code"`
	ErrorMessage  string       `json:"error_message"`
	StartedAt     sql.NullTime `json:"started_at"`
	FinishedAt    sql.NullTime `json:"finished_at"`
	CreatedAt     time.Time    `json:"created_at"`
	UpdatedAt     time.Time    `json:"updated_at"`
}

type WechatPublishJobEvent struct {
	ID        uint64    `json:"id"`
	JobID     uint64    `json:"job_id"`
	Status    string    `json:"status"`
	Message   string    `json:"message"`
	CreatedAt time.Time `json:"created_at"`
}
