// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package sqlc

import (
	"context"
	"database/sql"
)

type Querier interface {
	CreateUser(ctx context.Context, arg CreateUserParams) (sql.Result, error)
	GetUserByID(ctx context.Context, id uint64) (User, error)
	GetUserByUsername(ctx context.Context, username string) (User, error)
	SetUserStatus(ctx context.Context, arg SetUserStatusParams) (sql.Result, error)
	UpdateUserProfile(ctx context.Context, arg UpdateUserProfileParams) (sql.Result, error)
}

var _ Querier = (*Queries)(nil)
