// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: users.sql

package sqlc

import (
	"context"
	"database/sql"
)

const createUser = `-- name: CreateUser :execresult
INSERT INTO users (
    username,
    password_hash,
    nickname,
    avatar,
    role,
    status
) VALUES (?, ?, ?, ?, ?, ?)
`

type CreateUserParams struct {
	Username     string `json:"username"`
	PasswordHash string `json:"password_hash"`
	Nickname     string `json:"nickname"`
	Avatar       string `json:"avatar"`
	Role         string `json:"role"`
	Status       string `json:"status"`
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, createUser,
		arg.Username,
		arg.PasswordHash,
		arg.Nickname,
		arg.Avatar,
		arg.Role,
		arg.Status,
	)
}

const getUserByID = `-- name: GetUserByID :one
SELECT
    id,
    username,
    password_hash,
    nickname,
    avatar,
    role,
    status,
    created_at,
    updated_at
FROM users
WHERE id = ?
LIMIT 1
`

func (q *Queries) GetUserByID(ctx context.Context, id uint64) (User, error) {
	row := q.db.QueryRowContext(ctx, getUserByID, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.PasswordHash,
		&i.Nickname,
		&i.Avatar,
		&i.Role,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserByUsername = `-- name: GetUserByUsername :one
SELECT
    id,
    username,
    password_hash,
    nickname,
    avatar,
    role,
    status,
    created_at,
    updated_at
FROM users
WHERE username = ?
LIMIT 1
`

func (q *Queries) GetUserByUsername(ctx context.Context, username string) (User, error) {
	row := q.db.QueryRowContext(ctx, getUserByUsername, username)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.PasswordHash,
		&i.Nickname,
		&i.Avatar,
		&i.Role,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const setUserStatus = `-- name: SetUserStatus :execresult
UPDATE users
SET status = ?
WHERE id = ?
`

type SetUserStatusParams struct {
	Status string `json:"status"`
	ID     uint64 `json:"id"`
}

func (q *Queries) SetUserStatus(ctx context.Context, arg SetUserStatusParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, setUserStatus, arg.Status, arg.ID)
}

const updateUserProfile = `-- name: UpdateUserProfile :execresult
UPDATE users
SET
    nickname = ?,
    avatar = ?
WHERE id = ?
`

type UpdateUserProfileParams struct {
	Nickname string `json:"nickname"`
	Avatar   string `json:"avatar"`
	ID       uint64 `json:"id"`
}

func (q *Queries) UpdateUserProfile(ctx context.Context, arg UpdateUserProfileParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, updateUserProfile, arg.Nickname, arg.Avatar, arg.ID)
}
