<script setup lang="ts">
import type { Article } from '~/types/api';
const route = useRoute(); const { request } = useApi(); const article = ref<Article>(); const loading = ref(true); const assetURLs = computed(() => new Map((article.value?.assets || []).filter((asset) => asset.downloadStatus === 'completed' && asset.mediaUrl).map((asset) => [asset.id, asset.mediaUrl])));
onMounted(async () => { try { article.value = await request<Article>(`/articles/${route.params.id}`); } finally { loading.value = false; } });
function date(value?: string) { return value ? new Intl.DateTimeFormat('zh-CN', { dateStyle: 'long', timeStyle: 'short' }).format(new Date(value)) : ''; }
</script>

<template>
  <main class="wp-container py-10"><div v-if="loading" class="py-20 text-center text-gray-500">正在加载文章…</div><template v-else-if="article"><nav class="mb-6 flex items-center justify-between text-sm"><NuxtLink class="text-emerald-700" to="/articles">← 返回内容库</NuxtLink><a class="text-gray-500 hover:text-emerald-700" :href="article.originalUrl" rel="noopener noreferrer" target="_blank">查看原文 ↗</a></nav><article class="wp-card mx-auto max-w-4xl px-6 py-8 sm:px-12 sm:py-12"><header class="mb-10 border-b border-black/10 pb-8"><div class="mb-4 flex gap-2 text-xs"><span class="rounded-full bg-emerald-50 px-3 py-1 text-emerald-700">{{ article.sourceType === 'wechat' ? '微信公众号' : '普通网页' }}</span></div><h1 class="text-3xl font-bold leading-tight sm:text-4xl">{{ article.title }}</h1><p class="mt-4 text-sm text-gray-500">{{ article.sourceName || article.author || '未知来源' }} · {{ date(article.publishedAt || article.createdAt) }}</p></header><div class="article-body"><template v-for="(block, index) in article.blocks" :key="index"><component :is="`h${Math.min(Math.max(block.level || 2, 2), 4)}`" v-if="block.type === 'heading'">{{ block.text }}</component><p v-else-if="block.type === 'paragraph'">{{ block.text }}</p><blockquote v-else-if="block.type === 'quote'">{{ block.text }}</blockquote><pre v-else-if="block.type === 'code'"><code>{{ block.text }}</code></pre><li v-else-if="block.type === 'list'">{{ block.text }}</li><figure v-else-if="block.type === 'image' && block.assetId && assetURLs.get(block.assetId)"><img :alt="block.alt || ''" :src="assetURLs.get(block.assetId)" loading="lazy"><figcaption v-if="block.alt">{{ block.alt }}</figcaption></figure></template><p v-if="!article.blocks?.length" class="py-12 text-center text-gray-500">正文仍在处理中</p></div></article></template><div v-else class="py-20 text-center text-gray-500">文章不存在</div></main>
</template>
