<script setup lang="ts">
import type { Article, PageResult, SourceType } from '~/types/api';
const { request } = useApi(); const items = ref<Article[]>([]); const total = ref(0); const page = ref(1); const keyword = ref(''); const sourceType = ref<'' | SourceType>(''); const loading = ref(false);
async function load() { loading.value = true; try { const query = new URLSearchParams({ page: String(page.value), pageSize: '20', status: 'ready' }); if (keyword.value.trim()) query.set('keyword', keyword.value.trim()); if (sourceType.value) query.set('sourceType', sourceType.value); const data = await request<PageResult<Article>>(`/articles?${query}`); items.value = data.items; total.value = data.total; } finally { loading.value = false; } }
function search() { page.value = 1; void load(); } function date(value?: string) { return value ? new Intl.DateTimeFormat('zh-CN', { dateStyle: 'medium' }).format(new Date(value)) : ''; }
onMounted(load);
</script>

<template>
  <main class="wp-container py-10"><section class="mb-7"><h1 class="text-4xl font-bold">内容库</h1><p class="mt-2 text-gray-500">在一个干净、专注的空间里浏览团队收藏。</p></section><section class="wp-card mb-6 flex flex-col gap-3 p-4 sm:flex-row"><input v-model="keyword" class="min-w-0 flex-1 rounded-xl border border-black/10 bg-white px-4 py-2.5 outline-none focus:border-emerald-600" placeholder="搜索标题、作者或来源" @keyup.enter="search"><select v-model="sourceType" class="rounded-xl border border-black/10 bg-white px-4 py-2.5"><option value="">全部来源</option><option value="wechat">微信公众号</option><option value="web">普通网页</option></select><button class="rounded-xl bg-emerald-700 px-6 py-2.5 font-medium text-white" @click="search">搜索</button></section><div v-if="loading" class="py-20 text-center text-gray-500">正在加载…</div><section v-else class="space-y-3"><NuxtLink v-for="article in items" :key="article.id" :to="`/articles/${article.id}`" class="wp-card group block p-6"><div class="flex flex-col justify-between gap-4 sm:flex-row"><div><div class="mb-2 flex items-center gap-2 text-xs text-gray-500"><span class="text-emerald-700">{{ article.sourceType === 'wechat' ? '公众号' : '网页' }}</span><span>·</span><span>{{ article.sourceName || article.author || '未知来源' }}</span></div><h2 class="text-xl font-bold group-hover:text-emerald-700">{{ article.title }}</h2></div><time class="shrink-0 text-sm text-gray-400">{{ date(article.publishedAt || article.createdAt) }}</time></div></NuxtLink><div v-if="!items.length" class="wp-card py-20 text-center text-gray-500">没有找到匹配的内容</div></section><div v-if="total > 20" class="mt-8 flex items-center justify-center gap-4"><button :disabled="page <= 1" class="rounded-lg border px-4 py-2 disabled:opacity-40" @click="page--; load()">上一页</button><span class="text-sm text-gray-500">第 {{ page }} 页</span><button :disabled="page * 20 >= total" class="rounded-lg border px-4 py-2 disabled:opacity-40" @click="page++; load()">下一页</button></div></main>
</template>
